import { execSync } from 'child_process'
import { existsSync, mkdirSync, writeFileSync } from 'fs'
import { join, resolve } from 'path'

interface ProjectFiles {
  [relativePath: string]: string
}

export async function createApp(projectName: string): Promise<void> {
  const projectDir = resolve(process.cwd(), projectName)

  if (existsSync(projectDir)) {
    throw new Error(`Directory ${projectName} already exists`)
  }

  console.log(`\n  Creating Goleo project: ${projectName}\n`)

  // Create directory structure
const dirs = [
    'backend/app',
    'backend/commands',
    'backend/gomobile',
    'backend/frontend/dist',
    'frontend/src',
    'frontend/public',
    'frontend/dist',
]

  for (const dir of dirs) {
    mkdirSync(join(projectDir, dir), { recursive: true })
    console.log(`  created ${projectName}/${dir}/`)
  }

  // Write all project files
  const files: ProjectFiles = getProjectFiles(projectName)
  for (const [relPath, content] of Object.entries(files)) {
    const fullPath = join(projectDir, relPath)
    writeFileSync(fullPath, content, 'utf-8')
    console.log(`  created ${projectName}/${relPath}`)
  }

  // Install dependencies
  const frontendDir = join(projectDir, 'frontend')
  console.log('\n  Installing frontend dependencies...')

  try {
    execSync('npm install', { cwd: frontendDir, stdio: 'inherit' })
  } catch {
    // npm install failed (likely @goleo/bridge not published yet).
    // Try linking from global if available.
    console.log('  npm install failed. Checking for local @goleo/bridge...')
    try {
      execSync('npm link @goleo/bridge', { cwd: frontendDir, stdio: 'inherit' })
      console.log('  @goleo/bridge linked locally — retrying install...')
      execSync('npm install', { cwd: frontendDir, stdio: 'inherit' })
    } catch {
      console.log(`  Warning: could not install frontend dependencies.`)
      console.log(`  Run manually:`)
      console.log(`    cd ${projectName}/frontend`)
      console.log(`    npm link @goleo/bridge`)
      console.log(`    npm install`)
    }
  }

  console.log('\n  Project created successfully!\n')
  console.log('  Next steps:')
  console.log(`    cd ${projectName}`)
  console.log(`    cd frontend && npm link @goleo/bridge && npm install && cd ..`)
  console.log('    goleo dev')
  console.log('    goleo build')
  console.log('    goleo emulate android\n')
}

function getProjectFiles(name: string): ProjectFiles {
  return {
    'package.json': JSON.stringify({
      name,
      private: true,
      scripts: {
        'goleo:dev': 'goleo dev',
        'goleo:dev-pwa': 'goleo dev pwa',
        'goleo:build': 'goleo build',
        'goleo:build-windows': 'goleo build windows',
        'goleo:build-linux': 'goleo build linux',
        'goleo:build-darwin': 'goleo build darwin',
        'goleo:build-android': 'goleo build android',
        'goleo:build-ios': 'goleo build ios',
        'goleo:build-pwa': 'goleo build pwa',
        'goleo:emulate': 'goleo emulate android',
        'goleo:emulate-ios': 'goleo emulate ios',
      },
    }, null, 2) + '\n',

    'goleo.json': JSON.stringify({
      version: '0.1.0',
      app_name: name,
      frontend: {
        directory: 'frontend',
        build_command: 'npm run build',
        dev_command: 'npm run dev',
        dist_dir: 'dist',
      },
      mobile: {
        android: {
          min_sdk: 24,
          package_name: 'com.goleo.app',
        },
        ios: {
          deployment_target: '14.0',
          bundle_identifier: 'com.goleo.app',
        },
      },
    }, null, 2) + '\n',

    'go.mod': `module goleo/${name}\n\ngo 1.26\n\nrequire github.com/daforester/goleo v0.1.0\n`,

    '.gitignore': `# Generated by goleo — regenerated on every dev/build/emulate run, do not edit
/backend/main.go
/backend/gomobile/gomobile.go
/backend/gomobile/notifier.go

# Build staging and outputs
/.goleo/
/app
/app.exe
/app.apk
/app-dev.apk
*.aar
*.xcframework
GoleoApp.app/

# Frontend
/frontend/node_modules/
/frontend/dist/*
!/frontend/dist/.gitkeep
/backend/frontend/dist/*
!/backend/frontend/dist/.gitkeep
`,

    'backend/app/app.go': `package app

import (
	"context"
	"log"

	"goleo/${name}/backend/commands"
	"github.com/daforester/goleo/runtime"
)

// Options describes how this run differs across targets (desktop, mobile
// release, mobile dev). Everything else — command registration, feature
// wiring, shutdown logic — lives once, below, and applies to all of them.
type Options struct {
	DevMode    bool
	WindowMode runtime.WindowMode
	// EmbedFS is the caller's embedded frontend/dist (an embed.FS). Each
	// entry point embeds its own copy, since Go's //go:embed can only reach
	// files at or below the directory of the source file that declares it.
	EmbedFS any
}

// New builds this app's runtime.App. backend/main.go (desktop) and
// backend/gomobile/gomobile.go (mobile) both call this — add your own
// command registration and startup logic here, once, instead of
// per-entry-point.
func New(opts Options) *runtime.App {
	title := "${name}"
	if opts.DevMode {
		title += " (dev)"
	}

	var a *runtime.App
	a = runtime.New(runtime.Config{
		Title:      title,
		Width:      1024,
		Height:     768,
		DevMode:    opts.DevMode,
		Port:       9842,
		WindowMode: opts.WindowMode,
		EmbedFS:    opts.EmbedFS,
		// InitJS: "init.js", // custom startup script path (default: init.js, then backend/init.js); desktop only
		OnStartup: func(ctx context.Context) {
			log.Println(title, "starting up...")
			runtime.RegisterBuiltins(a.Bridge())
			if opts.WindowMode == runtime.WindowModeWebview {
				runtime.RegisterDesktopFeatures(a.Bridge())
			}
			commands.Register(a.Bridge())
			commands.StartHeartbeat(a.Bridge())
			// Uncomment and rebuild with the corresponding build tag to enable
			// permission-gated features on mobile.
			//   goleo build android -- -tags "goleo_nfc,goleo_ble"
			//
			// runtime.RegisterNFC(a.Bridge())
			// runtime.RegisterBLE(a.Bridge())
			// runtime.RegisterGeolocation(a.Bridge())
			// runtime.RegisterCamera(a.Bridge())
			// runtime.RegisterDialogs(a.Bridge())
			// runtime.RegisterFS(a.Bridge())
			// runtime.RegisterClipboard(a.Bridge())
			// runtime.RegisterSensors(a.Bridge())
			// runtime.RegisterVibration(a.Bridge())
			// runtime.RegisterWakeLock(a.Bridge())
			// runtime.RegisterBackground(a.Bridge())
			// runtime.RegisterPush(a.Bridge())
		},
		OnShutdown: func(ctx context.Context) {
			log.Println(title, "shutting down...")
		},
	})
	return a
}
`,

    'backend/init.js': `// init.js — Goleo startup script.
//
// Runs inside the Go backend (embedded JS engine) before any window is
// shown, giving you full control over window creation. Available API:
//
//   getConfig()       -> { title, width, height, devMode, devServer, port, url }
//   createWindow(opts) - opts: title, width, height, minWidth, minHeight,
//                        center, devTools, url (defaults to the app's own URL)
//   console.log/info/warn/error
//
// Available bridge commands (call via bridge.invoke("goleo:xxx", { ... })):
//
//   Core:
//     goleo:getOS                          -> OSInfo
//     goleo:getPlatform                    -> PlatformInfo
//     goleo:getArch                        -> string
//     goleo:getEnv({ key })                -> string
//     goleo:openURL({ url })               -> void
//     goleo:notify({ title, body? })       -> void
//     goleo:showMessage({ title, message }) -> void
//
//   Clipboard:
//     goleo:clipboardReadText              -> { text }
//     goleo:clipboardWriteText({ text })   -> void
//
//   Dialogs:
//     goleo:dialogOpenFile({ ... })        -> string[]
//     goleo:dialogSaveFile({ ... })        -> string
//     goleo:dialogSelectFolder({ ... })    -> string
//     goleo:dialogShowMessage({ ... })     -> { button }
//     goleo:dialogShowPrompt({ ... })      -> string
//
//   File System:
//     goleo:fsReadTextFile({ path })       -> string
//     goleo:fsWriteTextFile({ path, content }) -> void
//     goleo:fsReadBinaryFile({ path })     -> { data }
//     goleo:fsWriteBinaryFile({ path, data }) -> void
//     goleo:fsListDir({ path })            -> FileEntry[]
//     goleo:fsDelete({ path })             -> void
//     goleo:fsAppDataDir({ appName? })     -> string
//     goleo:fsHomeDir                      -> string
//
//   Geolocation:
//     goleo:geolocationGetCurrentPosition({ ... }) -> Position
//
// Delete this file (and its embed line in main.go) to fall back to the
// built-in window setup from runtime.Config.

const config = getConfig()

createWindow({
  title: config.title,
  width: config.width,
  height: config.height,
  center: true,
})
`,

    'backend/commands/commands.go': `package commands

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"runtime"
	"time"

	goleoruntime "github.com/daforester/goleo/runtime"
)

func Register(b *goleoruntime.Bridge) {
	b.Handle("greet", func(ctx context.Context, args json.RawMessage) (any, error) {
		var params map[string]string
		if err := json.Unmarshal(args, &params); err != nil {
			return nil, err
		}
		name := params["name"]
		if name == "" {
			name = "World"
		}
		return map[string]string{
			"message": fmt.Sprintf("Hello, %s! From Go backend at %s.", name, time.Now().Format(time.RFC3339)),
		}, nil
	})

	b.Handle("systemInfo", func(ctx context.Context, args json.RawMessage) (any, error) {
		return map[string]any{
			"goVersion":  runtime.Version(),
			"os":         runtime.GOOS,
			"arch":       runtime.GOARCH,
			"cpus":       runtime.NumCPU(),
			"goroutines": runtime.NumGoroutine(),
		}, nil
	})

	b.Handle("add", func(ctx context.Context, args json.RawMessage) (any, error) {
		var params map[string]float64
		if err := json.Unmarshal(args, &params); err != nil {
			return nil, fmt.Errorf("invalid args: need 'a' and 'b' numbers")
		}
		return map[string]float64{
			"result": params["a"] + params["b"],
		}, nil
	})

	b.Handle("countdown", func(ctx context.Context, args json.RawMessage) (any, error) {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-time.After(3 * time.Second):
			return map[string]string{
				"message": "3 seconds have passed! Async works.",
			}, nil
		}
	})

	b.Handle("notify", func(ctx context.Context, args json.RawMessage) (any, error) {
		var params map[string]string
		if err := json.Unmarshal(args, &params); err != nil {
			params = map[string]string{"title": "Notification", "message": string(args)}
		}
		if params["title"] == "" {
			params["title"] = "Goleo"
		}
		if params["message"] == "" {
			params["message"] = "Hello from Go!"
		}
		if err := goleoruntime.Notify(params["title"], params["message"]); err != nil {
			return nil, err
		}
		b.Emit("notification:show", params)
		return map[string]string{"status": "sent"}, nil
	})

	b.On("app:log", func(ctx context.Context, data json.RawMessage) {
		var msg string
		if err := json.Unmarshal(data, &msg); err != nil {
			msg = string(data)
		}
		log.Printf("[app:log] %s", msg)
	})
}

// StartHeartbeat emits a "heartbeat" event every 5 seconds with the current
// server time and active goroutine count. Call this in OnStartup to stream
// live data to the frontend.
func StartHeartbeat(b *goleoruntime.Bridge) {
	go func() {
		for {
			time.Sleep(5 * time.Second)
			b.Emit("heartbeat", map[string]any{
				"time":       time.Now().Format(time.RFC3339),
				"goroutines": runtime.NumGoroutine(),
			})
		}
	}()
}
`,

    'backend/frontend/dist/.gitkeep': '',

    'frontend/package.json': JSON.stringify({
      name: `${name}-frontend`,
      private: true,
      version: '0.0.0',
      type: 'module',
      scripts: {
        dev: 'vite',
        build: 'vite build',
        preview: 'vite preview',
      },
      dependencies: {
        vue: '^3.4.0',
        '@goleo/bridge': '^0.1.0',
      },
      devDependencies: {
        '@vitejs/plugin-vue': '^5.0.0',
        typescript: '^5.3.0',
        vite: '^5.0.0',
      },
    }, null, 2) + '\n',

    'frontend/index.html': `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${name}</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.ts"></script>
  </body>
</html>
`,

    'frontend/vite.config.ts': `import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  plugins: [vue()],
  server: {
    proxy: {
      '/api': 'http://localhost:9842',
      '/ws': {
        target: 'ws://localhost:9842',
        ws: true,
      },
    },
  },
  build: {
    outDir: 'dist',
    emptyOutDir: true,
  },
})
`,

    'frontend/tsconfig.json': JSON.stringify({
      compilerOptions: {
        target: 'ES2020',
        module: 'ESNext',
        lib: ['ES2020', 'DOM', 'DOM.Iterable'],
        skipLibCheck: true,
        moduleResolution: 'bundler',
        allowImportingTsExtensions: true,
        resolveJsonModule: true,
        isolatedModules: true,
        noEmit: true,
        jsx: 'preserve',
        strict: true,
        noUnusedLocals: true,
        noUnusedParameters: true,
        noFallthroughCasesInSwitch: true,
      },
      include: ['src/**/*.ts', 'src/**/*.tsx', 'src/**/*.vue', 'env.d.ts'],
    }, null, 2) + '\n',

    'frontend/env.d.ts': `/// <reference types="vite/client" />

declare module '*.vue' {
  import type { DefineComponent } from 'vue'
  const component: DefineComponent<{}, {}, any>
  export default component
}
`,

    'frontend/src/main.ts': `import { createApp } from 'vue'
import { initBridge } from '@goleo/bridge'
import App from './App.vue'
import './style.css'

async function main() {
  const isPWA = import.meta.env.VITE_GOLEO_PLATFORM === 'pwa'
  await initBridge({ backend: !isPWA })

  if (isPWA && 'serviceWorker' in navigator) {
    navigator.serviceWorker.register('/sw.js')
  }

  const app = createApp(App)
  app.mount('#app')
}

main()
`,

    'frontend/src/App.vue': `<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { invoke, getOSInfo, on, isConnected, sendEvent, isPermissionGranted, requestPermission } from '@goleo/bridge'

const osInfo = ref('')
const backendMessage = ref('')
const systemInfo = ref('')
const a = ref(0)
const b = ref(0)
const sumResult = ref<number | null>(null)
const countdownMessage = ref('')
const heartbeat = ref('')
const logInput = ref('')
const logStatus = ref('')
const notifyStatus = ref('')
const lastNotification = ref('')
const permStatus = ref('')

onMounted(async () => {
  const info = await getOSInfo()
  osInfo.value = JSON.stringify(info, null, 2)

  if (isConnected()) {
    try {
      const result = await invoke('greet', { name: 'Goleo' })
      backendMessage.value = result.message
    } catch (err) {
      backendMessage.value = 'Backend error: ' + err
    }
  } else {
    backendMessage.value = 'PWA mode — no Go backend'
  }

  permStatus.value = (await isPermissionGranted()) ? 'granted' : 'default'
})

on('bridge:connected', () => {
  console.log('Backend connected')
})

on('notification:show', (data: any) => {
  lastNotification.value = data.message || ''
})

on('heartbeat', (data: any) => {
  heartbeat.value = JSON.stringify(data)
})

async function fetchSystemInfo() {
  try {
    systemInfo.value = JSON.stringify(await invoke('systemInfo'), null, 2)
  } catch (err) {
    systemInfo.value = 'Error: ' + err
  }
}

async function doAdd() {
  try {
    const result = await invoke<{ result: number }>('add', { a: a.value, b: b.value })
    sumResult.value = result.result
  } catch (err) {
    sumResult.value = null
    countdownMessage.value = 'Add error: ' + err
  }
}

async function doCountdown() {
  countdownMessage.value = 'Waiting 3 seconds...'
  try {
    const result = await invoke<{ message: string }>('countdown')
    countdownMessage.value = result.message
  } catch (err) {
    countdownMessage.value = 'Countdown error: ' + err
  }
}

function doSendLog() {
  sendEvent('app:log', { text: logInput.value || 'Hello from frontend!' })
  logStatus.value = 'Event sent!'
}

async function requestNotifyPermission() {
  permStatus.value = 'requesting'
  const result = await requestPermission()
  permStatus.value = result
}

async function sendNativeNotify() {
  if (!(await isPermissionGranted())) {
    const result = await requestPermission()
    permStatus.value = result
    if (result !== 'granted') {
      notifyStatus.value = 'Permission denied'
      return
    }
  }
  notifyStatus.value = 'Sending...'
  await invoke('goleo:notify', {
    title: 'Hello from Goleo!',
    body: 'This notification was triggered via the Goleo bridge.',
  })
  notifyStatus.value = 'Notification sent!'
}
</script>

<template>
  <div class="container">
    <h1>Goleo App</h1>
    <p>OS Info:</p>
    <pre>{{ osInfo }}</pre>
    <p>Backend says: <strong>{{ backendMessage }}</strong></p>

    <hr />
    <h2>Custom Invoke — systemInfo</h2>
    <button @click="fetchSystemInfo" class="btn">Get System Info</button>
    <pre>{{ systemInfo }}</pre>

    <h2>Custom Invoke — add</h2>
    <input v-model.number="a" placeholder="a" class="input" /> +
    <input v-model.number="b" placeholder="b" class="input" />
    <button @click="doAdd" class="btn">=</button>
    <span v-if="sumResult !== null"><strong>{{ sumResult }}</strong></span>

    <h2>Custom Invoke — countdown (async)</h2>
    <button @click="doCountdown" class="btn">Start 3s Countdown</button>
    <p>{{ countdownMessage }}</p>

    <hr />
    <h2>Backend Event: heartbeat</h2>
    <p>Received every 5s from Go backend via <code>b.Emit("heartbeat", ...)</code>:</p>
    <pre>{{ heartbeat }}</pre>

    <h2>Frontend Event: app:log</h2>
    <p>Sent to Go backend via <code>sendEvent("app:log", ...)</code>:</p>
    <input v-model="logInput" placeholder="Log message" class="input" />
    <button @click="doSendLog" class="btn">Send to Backend</button>
    <p>{{ logStatus }}</p>

    <hr />
    <h2>Notifications Demo</h2>
    <p>Permission: <strong>{{ permStatus }}</strong></p>
    <button @click="requestNotifyPermission" class="btn">Request Permission</button>
    <button @click="sendNativeNotify" class="btn">Send System Notification</button>
    <p>{{ notifyStatus }}</p>
    <p>Last event: {{ lastNotification }}</p>
  </div>
</template>
`,

    'frontend/src/style.css': `* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen,
    Ubuntu, Cantarell, sans-serif;
  background-color: #f5f5f5;
  color: #333;
}

.container {
  max-width: 800px;
  margin: 0 auto;
  padding: 2rem;
}

h1 {
  font-size: 2rem;
  margin-bottom: 1rem;
  color: #2c3e50;
}

h2 {
  font-size: 1.5rem;
  margin: 1.5rem 0 0.5rem;
  color: #2c3e50;
}

pre {
  background: #eee;
  padding: 0.5rem;
  border-radius: 4px;
  overflow-x: auto;
}

hr {
  border: none;
  border-top: 1px solid #ddd;
  margin: 1.5rem 0;
}

.btn {
  display: inline-block;
  padding: 0.6rem 1.2rem;
  background: #42b883;
  color: #fff;
  border: none;
  border-radius: 6px;
  font-size: 1rem;
  cursor: pointer;
}

.btn:hover {
  background: #38a476;
}

.input {
  padding: 0.5rem 0.8rem;
  border: 1px solid #ccc;
  border-radius: 4px;
  font-size: 1rem;
  width: 80px;
  margin-right: 0.3rem;
}

.input[placeholder="Log message"] {
  width: 240px;
}

.status {
  margin-top: 0.5rem;
  font-size: 0.9rem;
  color: #666;
}
`,

    'frontend/public/sw.js': `const CACHE_NAME = 'goleo-pwa-v1'

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      return cache.addAll([
        '/',
        '/index.html',
      ])
    })
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames
          .filter((name) => name !== CACHE_NAME)
          .map((name) => caches.delete(name))
      )
    })
  )
})

self.addEventListener('fetch', (event) => {
  event.respondWith(
    caches.match(event.request).then((response) => {
      return response || fetch(event.request)
    })
  )
})
`,

    'frontend/public/manifest.json': JSON.stringify({
      name: '${name}',
      short_name: '${name}',
      start_url: '/',
      display: 'standalone',
      background_color: '#ffffff',
      theme_color: '#000000',
      description: '${name} - Built with Goleo',
    }, null, 2) + '\n',

    'frontend/dist/.gitkeep': '',

  }
}
