package cmd

import (
	"crypto/ed25519"
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

var generateCmd = &cobra.Command{
	Use:   "generate",
	Short: "Generate code from the project schema",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
}

var generateTypesCmd = &cobra.Command{
	Use:   "types",
	Short: "Generate TypeScript type declarations for the bridge API",
	Long: `Generate a goleo.d.ts file with fully typed invoke overloads
and convenience function declarations for all built-in bridge commands.

The generated file is placed at frontend/src/goleo.d.ts by default.

Usage:
  goleo generate types                    # default path
  goleo generate types --output ./src/generated.d.ts`,
	RunE: runGenerateTypes,
}

var generateUpdaterKeyCmd = &cobra.Command{
	Use:   "updater-key",
	Short: "Generate an ed25519 keypair for signing update manifests",
	Long: `Generate an ed25519 keypair for the auto-updater.

Set the private key as GOLEO_UPDATE_PRIVKEY when running
` + "`goleo build --publish`" + `, and embed the public key in your app's
RegisterUpdater config (UpdaterConfig.PublicKey).`,
	RunE: func(cmd *cobra.Command, args []string) error {
		pub, priv, err := ed25519.GenerateKey(rand.Reader)
		if err != nil {
			return fmt.Errorf("generating key: %w", err)
		}
		fmt.Println("Private key — keep secret; set as GOLEO_UPDATE_PRIVKEY when publishing:")
		fmt.Println("  " + base64.StdEncoding.EncodeToString(priv))
		fmt.Println()
		fmt.Println("Public key — embed in RegisterUpdater(UpdaterConfig{PublicKey: ...}):")
		fmt.Println("  " + base64.StdEncoding.EncodeToString(pub))
		return nil
	},
}

func init() {
	rootCmd.AddCommand(generateCmd)
	generateCmd.AddCommand(generateTypesCmd)
	generateCmd.AddCommand(generateUpdaterKeyCmd)
	generateTypesCmd.Flags().StringP("output", "o", "", "Output path for the generated types")
}

func runGenerateTypes(cmd *cobra.Command, args []string) error {
	output, _ := cmd.Flags().GetString("output")
	if output == "" {
		output = filepath.Join("frontend", "src", "goleo.d.ts")
	}

	dir := filepath.Dir(output)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}

	var b strings.Builder

	b.WriteString("// Auto-generated by `goleo generate types`\n")
	b.WriteString("// Do not edit manually. Re-run `goleo generate types` to update.\n")
	b.WriteString("\n")
	b.WriteString("import type { OSInfo, PlatformInfo } from '@goleo/bridge'\n")
	b.WriteString("\n")
	b.WriteString("/* eslint-disable */\n")
	b.WriteString("\n")

	// Augment the Bridge class invoke method with overloads
	b.WriteString("declare module '@goleo/bridge' {\n")
	b.WriteString("  interface Bridge {\n")

	for _, c := range KnownCommands {
		argsPart := ""
		if c.Args != "" {
			argsPart = fmt.Sprintf("args: %s", c.Args)
		}
		b.WriteString(fmt.Sprintf("    invoke(method: '%s'%s): Promise<%s>\n", c.Method, optionalArgs(argsPart), c.ReturnType))
	}

	b.WriteString("  }\n")
	b.WriteString("}\n")
	b.WriteString("\n")

	// Also generate standalone invoke overloads
	b.WriteString("declare module '@goleo/bridge' {\n")
	b.WriteString("  export function invoke<T = unknown>(method: string, args?: Record<string, unknown>): Promise<T>\n")

	for _, c := range KnownCommands {
		argsPart := ""
		if c.Args != "" {
			argsPart = fmt.Sprintf("args: %s", c.Args)
		}
		b.WriteString(fmt.Sprintf("  export function invoke(method: '%s'%s): Promise<%s>\n", c.Method, optionalArgs(argsPart), c.ReturnType))
	}

	b.WriteString("}\n")

	if err := os.WriteFile(output, []byte(b.String()), 0644); err != nil {
		return fmt.Errorf("write types file: %w", err)
	}

	abs, _ := filepath.Abs(output)
	fmt.Printf("Generated bridge type declarations → %s\n", abs)
	fmt.Printf("  %d built-in commands typed\n", len(KnownCommands))

	// The backend's init.js had no types at all, which is how it came to ship a comment
	// block documenting a `bridge` object the engine never defined: with nothing to check
	// against, the prose was the only reference and it drifted unchallenged. Emit
	// declarations for the globals the JS engine really provides, so an editor
	// resolves them and flags anything else as undefined.
	//
	// Skipped when there is no backend/ — `generate types` is also useful in a bare
	// frontend, and creating a backend directory as a side effect would be surprising.
	if st, err := os.Stat("backend"); err == nil && st.IsDir() {
		dts := filepath.Join("backend", "init.d.ts")
		if err := os.WriteFile(dts, []byte(initDTS), 0644); err != nil {
			return fmt.Errorf("write init.d.ts: %w", err)
		}
		dtsAbs, _ := filepath.Abs(dts)
		fmt.Printf("Generated init.js declarations    → %s\n", dtsAbs)
	}
	return nil
}

// initDTS declares the globals runtime/jsruntime.go's provideAPI installs — and nothing
// else, which is the point. TestScaffoldInitJSDoesNotClaimABridge and
// TestVMDefinesExactlyTheDocumentedGlobals hold this file, the scaffold's comment block
// and the VM to the same set, so the three cannot drift apart again.
//
// `console` is deliberately NOT declared: TypeScript's own lib already provides it, and
// redeclaring it is a "cannot redeclare block-scoped variable" error in any project that
// includes the DOM or ES libs. The comment records what the engine actually supplies.
const initDTS = `// Auto-generated by ` + "`goleo generate types`" + `
// Do not edit manually. Re-run ` + "`goleo generate types`" + ` to update.
//
// Types for backend/init.js, which runs inside the Go backend's embedded JS engine.
// These four globals are everything that engine defines.
//
// Bridge commands are reachable via goleo.invoke, through the SAME Policy ACL the
// frontend goes through — a script cannot reach a command the app has not allowed.
// There is no bare ` + "`bridge`" + ` object; older scaffolds documented one that never existed.
//
// ` + "`console`" + ` is provided by the engine (log / info / warn / error only) but is not
// declared here, because TypeScript's own lib already declares it.

/* eslint-disable */

/** What getConfig() returns: runtime.Config's values, plus the resolved port and URL. */
interface GoleoConfig {
  title: string
  width: number
  height: number
  devMode: boolean
  devServer: string
  /** The port the backend actually bound — not necessarily Config.Port, which can fall forward. */
  port: number
  /** The app's own URL, and createWindow's default target. */
  url: string
}

/** Options for createWindow(). Every field falls back to the Config value shown. */
interface GoleoWindowOptions {
  /** default: Config.Title */
  title?: string
  /** default: Config.Width */
  width?: number
  /** default: Config.Height */
  height?: number
  /** default: 0 (no minimum) */
  minWidth?: number
  /** default: 0 (no minimum) */
  minHeight?: number
  /** default: true */
  center?: boolean
  /** default: Config.DevMode */
  devTools?: boolean
  /** default: the app's own URL */
  url?: string
}

declare function getConfig(): GoleoConfig

/**
 * Opens a native window.
 *
 * Returns false in browser mode (goleo dev, goleo emulate, mobile), where there is no
 * native window to create — not an error, just nothing to do.
 */
declare function createWindow(opts?: GoleoWindowOptions): boolean

/** The bridge, from the script's side. */
interface GoleoAPI {
  /**
   * Calls a bridge command — the same ones the frontend uses.
   *
   * Synchronous: Go's handlers are, so there is no Promise. THROWS on failure,
   * including "permission denied" when a Policy is set, so wrap in try/catch if the
   * command may legitimately be disallowed.
   */
  invoke(method: string, args?: unknown): any
  /**
   * Pushes an event to the FRONTEND (backend -> frontend).
   *
   * Not the mirror of Go's app.On, which receives events coming FROM the frontend.
   */
  emit(event: string, payload?: unknown): void
}

declare const goleo: GoleoAPI
`

func optionalArgs(s string) string {
	if s == "" {
		return ""
	}
	return ", " + s
}
