package cmd

import (
	"crypto/ed25519"
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

var generateCmd = &cobra.Command{
	Use:   "generate",
	Short: "Generate code from the project schema",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
}

var generateTypesCmd = &cobra.Command{
	Use:   "types",
	Short: "Generate TypeScript type declarations for the bridge API",
	Long: `Generate a goleo.d.ts file with fully typed invoke overloads
and convenience function declarations for all built-in bridge commands.

The generated file is placed at frontend/src/goleo.d.ts by default.

Usage:
  goleo generate types                    # default path
  goleo generate types --output ./src/generated.d.ts`,
	RunE: runGenerateTypes,
}

var generateUpdaterKeyCmd = &cobra.Command{
	Use:   "updater-key",
	Short: "Generate an ed25519 keypair for signing update manifests",
	Long: `Generate an ed25519 keypair for the auto-updater.

Set the private key as GOLEO_UPDATE_PRIVKEY when running
` + "`goleo build --publish`" + `, and embed the public key in your app's
RegisterUpdater config (UpdaterConfig.PublicKey).`,
	RunE: func(cmd *cobra.Command, args []string) error {
		pub, priv, err := ed25519.GenerateKey(rand.Reader)
		if err != nil {
			return fmt.Errorf("generating key: %w", err)
		}
		fmt.Println("Private key — keep secret; set as GOLEO_UPDATE_PRIVKEY when publishing:")
		fmt.Println("  " + base64.StdEncoding.EncodeToString(priv))
		fmt.Println()
		fmt.Println("Public key — embed in RegisterUpdater(UpdaterConfig{PublicKey: ...}):")
		fmt.Println("  " + base64.StdEncoding.EncodeToString(pub))
		return nil
	},
}

func init() {
	rootCmd.AddCommand(generateCmd)
	generateCmd.AddCommand(generateTypesCmd)
	generateCmd.AddCommand(generateUpdaterKeyCmd)
	generateTypesCmd.Flags().StringP("output", "o", "", "Output path for the generated types")
}

func runGenerateTypes(cmd *cobra.Command, args []string) error {
	output, _ := cmd.Flags().GetString("output")
	if output == "" {
		output = filepath.Join("frontend", "src", "goleo.d.ts")
	}

	dir := filepath.Dir(output)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}

	var b strings.Builder

	b.WriteString("// Auto-generated by `goleo generate types`\n")
	b.WriteString("// Do not edit manually. Re-run `goleo generate types` to update.\n")
	b.WriteString("\n")
	b.WriteString("import type { OSInfo, PlatformInfo } from '@goleo/bridge'\n")
	b.WriteString("\n")
	b.WriteString("/* eslint-disable */\n")
	b.WriteString("\n")

	// Augment the Bridge class invoke method with overloads
	b.WriteString("declare module '@goleo/bridge' {\n")
	b.WriteString("  interface Bridge {\n")

	for _, c := range KnownCommands {
		argsPart := ""
		if c.Args != "" {
			argsPart = fmt.Sprintf("args: %s", c.Args)
		}
		b.WriteString(fmt.Sprintf("    invoke(method: '%s'%s): Promise<%s>\n", c.Method, optionalArgs(argsPart), c.ReturnType))
	}

	b.WriteString("  }\n")
	b.WriteString("}\n")
	b.WriteString("\n")

	// Also generate standalone invoke overloads
	b.WriteString("declare module '@goleo/bridge' {\n")
	b.WriteString("  export function invoke<T = unknown>(method: string, args?: Record<string, unknown>): Promise<T>\n")

	for _, c := range KnownCommands {
		argsPart := ""
		if c.Args != "" {
			argsPart = fmt.Sprintf("args: %s", c.Args)
		}
		b.WriteString(fmt.Sprintf("  export function invoke(method: '%s'%s): Promise<%s>\n", c.Method, optionalArgs(argsPart), c.ReturnType))
	}

	b.WriteString("}\n")

	if err := os.WriteFile(output, []byte(b.String()), 0644); err != nil {
		return fmt.Errorf("write types file: %w", err)
	}

	abs, _ := filepath.Abs(output)
	fmt.Printf("Generated bridge type declarations → %s\n", abs)
	fmt.Printf("  %d built-in commands typed\n", len(KnownCommands))
	return nil
}

func optionalArgs(s string) string {
	if s == "" {
		return ""
	}
	return ", " + s
}
