package cmd

var tmplAppGo = `package app

import (
	"context"
	"log"

	"{{.ModuleName}}/backend/commands"
	"github.com/daforester/goleo/runtime"
)

// Options describes how this run differs across targets (desktop, mobile
// release, mobile dev). Everything else — command registration, feature
// wiring, shutdown logic — lives once, below, and applies to all of them.
type Options struct {
	DevMode    bool
	WindowMode runtime.WindowMode
	// EmbedFS is the caller's embedded frontend/dist (an embed.FS). Each
	// entry point embeds its own copy, since Go's //go:embed can only reach
	// files at or below the directory of the source file that declares it.
	EmbedFS any
}

// New builds this app's runtime.App. backend/main.go (desktop) and
// backend/gomobile/gomobile.go (mobile) both call this — add your own
// command registration and startup logic here, once, instead of
// per-entry-point.
func New(opts Options) *runtime.App {
	title := "{{.Name}}"
	if opts.DevMode {
		title += " (dev)"
	}

	var a *runtime.App
	a = runtime.New(runtime.Config{
		Title:      title,
		Width:      1024,
		Height:     768,
		DevMode:    opts.DevMode,
		Port:       9842,
		WindowMode: opts.WindowMode,
		EmbedFS:    opts.EmbedFS,
		// InitJS: "init.js", // custom startup script path (default: init.js, then backend/init.js); desktop only
		OnStartup: func(ctx context.Context) {
			log.Println(title, "starting up...")
			runtime.RegisterBuiltins(a.Bridge())
			if opts.WindowMode == runtime.WindowModeWebview {
				runtime.RegisterDesktopFeatures(a.Bridge())
			}
			commands.Register(a.Bridge())
			commands.StartHeartbeat(a.Bridge())
			// Mobile permission-gated features: uncomment what your app uses.
			// The build tag each one needs (e.g. goleo_camera) is detected
			// automatically from this file by goleo build android/ios and
			// goleo emulate — see detectFeatureUsage in cli/cmd/scan.go — so
			// you don't need to pass -tags by hand.
			//
			// Battery, WakeLock, Geolocation, Camera, Clipboard, Dialogs, FS,
			// Sensors, Background, NFC and BLE all have working native
			// providers on Android (+ best-effort, unverified iOS — see
			// AppDelegate.swift) and/or a WebView browser-API fallback.
			// Push is the exception: it additionally needs your own
			// Firebase/Apple Developer project no matter what native code
			// exists — see cli/cmd/templates/android/.../MainActivity.java
			// for what's actually implemented.
			//
			// runtime.RegisterBattery(a.Bridge())
			// runtime.RegisterWakeLock(a.Bridge())
			// runtime.RegisterGeolocation(a.Bridge())
			// runtime.RegisterCamera(a.Bridge())
			// runtime.RegisterClipboard(a.Bridge())
			// runtime.RegisterDialogs(a.Bridge())
			// runtime.RegisterVibration(a.Bridge())
			// runtime.RegisterFS(a.Bridge())
			// runtime.RegisterSensors(a.Bridge())
			// runtime.RegisterBackground(a.Bridge())
			// runtime.RegisterNFC(a.Bridge())
			// runtime.RegisterBLE(a.Bridge())
			// runtime.RegisterPush(a.Bridge())
		},
		OnShutdown: func(ctx context.Context) {
			log.Println(title, "shutting down...")
		},
	})
	return a
}
`

var tmplMainGo = `// Code generated by goleo. DO NOT EDIT.
// Edit backend/app/app.go instead — this file is regenerated on every
// goleo dev/build/emulate run.

package main

import (
	"embed"
	"log"
	"os"

	"{{.ModuleName}}/backend/app"
	"github.com/daforester/goleo/runtime"
)

// Embedded application assets: the built frontend plus the startup script.
// goleo build copies frontend/dist here before compiling.
// If you delete init.js, also remove its embed line below — the app then
// falls back to the window settings in runtime.Config.
//
//go:embed all:frontend/dist
//go:embed init.js
var appFS embed.FS

func main() {
	a := app.New(app.Options{
		DevMode:    os.Getenv("GOLEO_DEV") == "true",
		WindowMode: runtime.WindowModeWebview,
		EmbedFS:    appFS,
	})

	if err := a.Run(); err != nil {
		log.Fatal(err)
	}
}
`

var tmplInitJS = `// init.js — Goleo startup script.
//
// Runs inside the Go backend (embedded JS engine) before any window is
// shown, giving you full control over window creation. Available API:
//
//   getConfig()       -> { title, width, height, devMode, devServer, port, url }
//   createWindow(opts) - opts: title, width, height, minWidth, minHeight,
//                        center, devTools, url (defaults to the app's own URL)
//   console.log/info/warn/error
//
// Available bridge commands (call via bridge.invoke("goleo:xxx", { ... })):
//
//   Core:
//     goleo:getOS                          -> OSInfo
//     goleo:getPlatform                    -> PlatformInfo
//     goleo:getArch                        -> string
//     goleo:getEnv({ key })                -> string
//     goleo:openURL({ url })               -> void
//     goleo:notify({ title, body? })       -> void
//     goleo:showMessage({ title, message }) -> void
//
//   Clipboard:
//     goleo:clipboardReadText              -> { text }
//     goleo:clipboardWriteText({ text })   -> void
//
//   Dialogs:
//     goleo:dialogOpenFile({ ... })        -> string[]
//     goleo:dialogSaveFile({ ... })        -> string
//     goleo:dialogSelectFolder({ ... })    -> string
//     goleo:dialogShowMessage({ ... })     -> { button }
//     goleo:dialogShowPrompt({ ... })      -> string
//
//   File System:
//     goleo:fsReadTextFile({ path })       -> string
//     goleo:fsWriteTextFile({ path, content }) -> void
//     goleo:fsReadBinaryFile({ path })     -> { data }
//     goleo:fsWriteBinaryFile({ path, data }) -> void
//     goleo:fsListDir({ path })            -> FileEntry[]
//     goleo:fsDelete({ path })             -> void
//     goleo:fsAppDataDir({ appName? })     -> string
//     goleo:fsHomeDir                      -> string
//
//   Geolocation:
//     goleo:geolocationGetCurrentPosition({ ... }) -> Position
//
// Delete this file (and its embed line in main.go) to fall back to the
// built-in window setup from runtime.Config.

const config = getConfig()

createWindow({
  title: config.title,
  width: config.width,
  height: config.height,
  center: true,
})
`

var tmplBackendCommandsGo = `package commands

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"runtime"
	"time"

	goleoruntime "github.com/daforester/goleo/runtime"
)

func Register(b *goleoruntime.Bridge) {
	b.Handle("greet", func(ctx context.Context, args json.RawMessage) (any, error) {
		var params map[string]string
		if err := json.Unmarshal(args, &params); err != nil {
			return nil, err
		}
		name := params["name"]
		if name == "" {
			name = "World"
		}
		return map[string]string{
			"message": fmt.Sprintf("Hello, %s! From Go backend at %s.", name, time.Now().Format(time.RFC3339)),
		}, nil
	})

	b.Handle("systemInfo", func(ctx context.Context, args json.RawMessage) (any, error) {
		return map[string]any{
			"goVersion":  runtime.Version(),
			"os":         runtime.GOOS,
			"arch":       runtime.GOARCH,
			"cpus":       runtime.NumCPU(),
			"goroutines": runtime.NumGoroutine(),
		}, nil
	})

	b.Handle("add", func(ctx context.Context, args json.RawMessage) (any, error) {
		var params map[string]float64
		if err := json.Unmarshal(args, &params); err != nil {
			return nil, fmt.Errorf("invalid args: need 'a' and 'b' numbers")
		}
		return map[string]float64{
			"result": params["a"] + params["b"],
		}, nil
	})

	b.Handle("countdown", func(ctx context.Context, args json.RawMessage) (any, error) {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-time.After(3 * time.Second):
			return map[string]string{
				"message": "3 seconds have passed! Async works.",
			}, nil
		}
	})

	b.Handle("notify", func(ctx context.Context, args json.RawMessage) (any, error) {
		var params map[string]string
		if err := json.Unmarshal(args, &params); err != nil {
			params = map[string]string{"title": "Notification", "message": string(args)}
		}
		if params["title"] == "" {
			params["title"] = "Goleo"
		}
		if params["message"] == "" {
			params["message"] = "Hello from Go!"
		}
		if err := goleoruntime.Notify(params["title"], params["message"]); err != nil {
			return nil, err
		}
		b.Emit("notification:show", params)
		return map[string]string{"status": "sent"}, nil
	})

	b.On("app:log", func(ctx context.Context, data json.RawMessage) {
		var msg string
		if err := json.Unmarshal(data, &msg); err != nil {
			msg = string(data)
		}
		log.Printf("[app:log] %s", msg)
	})
}

// StartHeartbeat emits a "heartbeat" event every 5 seconds with the current
// server time and active goroutine count. Call this in OnStartup to stream
// live data to the frontend.
func StartHeartbeat(b *goleoruntime.Bridge) {
	go func() {
		for {
			time.Sleep(5 * time.Second)
			b.Emit("heartbeat", map[string]any{
				"time":       time.Now().Format(time.RFC3339),
				"goroutines": runtime.NumGoroutine(),
			})
		}
	}()
}
`

var tmplGoMod = `module {{.ModuleName}}

go 1.26

require github.com/daforester/goleo v0.1.0
`

var tmplFrontendPackageJSON = `{
  "name": "{{.Name}}-frontend",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@goleo/bridge": "^0.1.0",
    "vue": "^3.4.0"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.0.0",
    "typescript": "^5.3.0",
    "vite": "^5.0.0"
  }
}
`

var tmplIndexHTML = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{.Name}}</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.ts"></script>
  </body>
</html>
`

var tmplViteConfig = `import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  plugins: [vue()],
  server: {
    proxy: {
      '/api': 'http://localhost:9842',
      '/ws': {
        target: 'ws://localhost:9842',
        ws: true,
      },
    },
  },
  build: {
    outDir: 'dist',
    emptyOutDir: true,
  },
})
`

var tmplTsconfig = `{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForExpose": true,
    "module": "ESNext",
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve",
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src/**/*.ts", "src/**/*.tsx", "src/**/*.vue", "env.d.ts"]
}
`

var tmplEnvDTS = `/// <reference types="vite/client" />

declare module '*.vue' {
  import type { DefineComponent } from 'vue'
  const component: DefineComponent<{}, {}, any>
  export default component
}
`

var tmplSWJS = `const CACHE_NAME = 'goleo-pwa-v1'

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      return cache.addAll([
        '/',
        '/index.html',
      ])
    })
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames
          .filter((name) => name !== CACHE_NAME)
          .map((name) => caches.delete(name))
      )
    })
  )
})

self.addEventListener('fetch', (event) => {
  event.respondWith(
    caches.match(event.request).then((response) => {
      return response || fetch(event.request)
    })
  )
})
`

var tmplManifestJSON = `{
  "name": "{{.Name}}",
  "short_name": "{{.Name}}",
  "start_url": "/",
  "display": "standalone",
  "background_color": "#ffffff",
  "theme_color": "#000000",
  "description": "{{.Name}} - Built with Goleo"
}
`

var tmplMainTS = `import { createApp } from 'vue'
import { initBridge } from '@goleo/bridge'
import App from './App.vue'
import './style.css'

async function main() {
  const isPWA = import.meta.env.VITE_GOLEO_PLATFORM === 'pwa'
  await initBridge({ backend: !isPWA })

  if (isPWA && 'serviceWorker' in navigator) {
    navigator.serviceWorker.register('/sw.js')
  }

  const app = createApp(App)
  app.mount('#app')
}

main()
`

var tmplAppVue = `<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { invoke, getOSInfo, on, isConnected, sendEvent, isPermissionGranted, requestPermission } from '@goleo/bridge'

const osInfo = ref('')
const backendMessage = ref('')
const systemInfo = ref('')
const a = ref(0)
const b = ref(0)
const sumResult = ref<number | null>(null)
const countdownMessage = ref('')
const heartbeat = ref('')
const logInput = ref('')
const logStatus = ref('')
const notifyStatus = ref('')
const lastNotification = ref('')
const permStatus = ref('')

onMounted(async () => {
  const info = await getOSInfo()
  osInfo.value = JSON.stringify(info, null, 2)

  if (isConnected()) {
    try {
      const result = await invoke('greet', { name: 'Goleo' })
      backendMessage.value = result.message
    } catch (err) {
      backendMessage.value = 'Backend error: ' + err
    }
  } else {
    backendMessage.value = 'PWA mode — no Go backend'
  }

  permStatus.value = (await isPermissionGranted()) ? 'granted' : 'default'
})

on('bridge:connected', () => {
  console.log('Backend connected')
})

on('notification:show', (data: any) => {
  lastNotification.value = data.message || ''
})

on('heartbeat', (data: any) => {
  heartbeat.value = JSON.stringify(data)
})

async function fetchSystemInfo() {
  try {
    systemInfo.value = JSON.stringify(await invoke('systemInfo'), null, 2)
  } catch (err) {
    systemInfo.value = 'Error: ' + err
  }
}

async function doAdd() {
  try {
    const result = await invoke<{ result: number }>('add', { a: a.value, b: b.value })
    sumResult.value = result.result
  } catch (err) {
    sumResult.value = null
    countdownMessage.value = 'Add error: ' + err
  }
}

async function doCountdown() {
  countdownMessage.value = 'Waiting 3 seconds...'
  try {
    const result = await invoke<{ message: string }>('countdown')
    countdownMessage.value = result.message
  } catch (err) {
    countdownMessage.value = 'Countdown error: ' + err
  }
}

function doSendLog() {
  sendEvent('app:log', { text: logInput.value || 'Hello from frontend!' })
  logStatus.value = 'Event sent!'
}

async function requestNotifyPermission() {
  permStatus.value = 'requesting'
  const result = await requestPermission()
  permStatus.value = result
}

async function sendNativeNotify() {
  if (!(await isPermissionGranted())) {
    const result = await requestPermission()
    permStatus.value = result
    if (result !== 'granted') {
      notifyStatus.value = 'Permission denied'
      return
    }
  }
  notifyStatus.value = 'Sending...'
  await invoke('goleo:notify', {
    title: 'Hello from Goleo!',
    body: 'This notification was triggered via the Goleo bridge.',
  })
  notifyStatus.value = 'Notification sent!'
}
</script>

<template>
  <div class="container">
    <h1>Goleo App</h1>
    <p>OS Info:</p>
    <pre>{{"{{"}} osInfo }}</pre>
    <p>Backend says: <strong>{{"{{"}} backendMessage }}</strong></p>

    <hr />
    <h2>Custom Invoke — systemInfo</h2>
    <button @click="fetchSystemInfo" class="btn">Get System Info</button>
    <pre>{{"{{"}} systemInfo }}</pre>

    <h2>Custom Invoke — add</h2>
    <input v-model.number="a" placeholder="a" class="input" /> +
    <input v-model.number="b" placeholder="b" class="input" />
    <button @click="doAdd" class="btn">=</button>
    <span v-if="sumResult !== null"><strong>{{"{{"}} sumResult }}</strong></span>

    <h2>Custom Invoke — countdown (async)</h2>
    <button @click="doCountdown" class="btn">Start 3s Countdown</button>
    <p>{{"{{"}} countdownMessage }}</p>

    <hr />
    <h2>Backend Event: heartbeat</h2>
    <p>Received every 5s from Go backend via <code>b.Emit("heartbeat", ...)</code>:</p>
    <pre>{{"{{"}} heartbeat }}</pre>

    <h2>Frontend Event: app:log</h2>
    <p>Sent to Go backend via <code>sendEvent("app:log", ...)</code>:</p>
    <input v-model="logInput" placeholder="Log message" class="input" />
    <button @click="doSendLog" class="btn">Send to Backend</button>
    <p>{{"{{"}} logStatus }}</p>

    <hr />
    <h2>Notifications Demo</h2>
    <p>Permission: <strong>{{"{{"}} permStatus }}</strong></p>
    <button @click="requestNotifyPermission" class="btn">Request Permission</button>
    <button @click="sendNativeNotify" class="btn">Send System Notification</button>
    <p>{{"{{"}} notifyStatus }}</p>
    <p>Last event: {{"{{"}} lastNotification }}</p>
  </div>
</template>
`

var tmplStyleCSS = `* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen,
    Ubuntu, Cantarell, sans-serif;
  background-color: #f5f5f5;
  color: #333;
}

.container {
  max-width: 800px;
  margin: 0 auto;
  padding: 2rem;
}

h1 {
  font-size: 2rem;
  margin-bottom: 1rem;
  color: #2c3e50;
}

h2 {
  font-size: 1.5rem;
  margin: 1.5rem 0 0.5rem;
  color: #2c3e50;
}

pre {
  background: #eee;
  padding: 0.5rem;
  border-radius: 4px;
  overflow-x: auto;
}

hr {
  border: none;
  border-top: 1px solid #ddd;
  margin: 1.5rem 0;
}

.btn {
  display: inline-block;
  padding: 0.6rem 1.2rem;
  background: #42b883;
  color: #fff;
  border: none;
  border-radius: 6px;
  font-size: 1rem;
  cursor: pointer;
}

.btn:hover {
  background: #38a476;
}

.input {
  padding: 0.5rem 0.8rem;
  border: 1px solid #ccc;
  border-radius: 4px;
  font-size: 1rem;
  width: 80px;
  margin-right: 0.3rem;
}

.input[placeholder="Log message"] {
  width: 240px;
}

.status {
  margin-top: 0.5rem;
  font-size: 0.9rem;
  color: #666;
}
`

var tmplRootPackageJSON = `{
  "name": "{{.Name}}",
  "private": true,
  "scripts": {
    "goleo:dev": "goleo dev",
    "goleo:dev-pwa": "goleo dev pwa",
    "goleo:build": "goleo build",
    "goleo:build-windows": "goleo build windows",
    "goleo:build-linux": "goleo build linux",
    "goleo:build-darwin": "goleo build darwin",
    "goleo:build-android": "goleo build android",
    "goleo:build-ios": "goleo build ios",
    "goleo:build-pwa": "goleo build pwa",
    "goleo:emulate": "goleo emulate android",
    "goleo:emulate-ios": "goleo emulate ios"
  }
}
`

var tmplGoleoJSON = `{
  "version": "0.1.0",
  "app_name": "{{.Name}}",
  "frontend": {
    "directory": "frontend",
    "build_command": "npm run build",
    "dev_command": "npm run dev",
    "dist_dir": "dist"
  },
  "mobile": {
    "android": {
      "min_sdk": 24,
      "package_name": "com.goleo.app"
    },
    "ios": {
      "deployment_target": "14.0",
      "bundle_identifier": "com.goleo.app"
    }
  }
}
`

var tmplGitignore = `# Generated by goleo — regenerated on every dev/build/emulate run, do not edit
/backend/main.go
/backend/gomobile/gomobile.go
/backend/gomobile/notifier.go

# Build staging and outputs
/.goleo/
/app
/app.exe
/app.apk
/app-dev.apk
*.aar
*.xcframework
GoleoApp.app/

# Frontend
/frontend/node_modules/
/frontend/dist/*
!/frontend/dist/.gitkeep
/backend/frontend/dist/*
!/backend/frontend/dist/.gitkeep
`

var tmplMobileGo = `// Code generated by goleo. DO NOT EDIT.
// Edit backend/app/app.go instead — this file is regenerated on every
// goleo dev/build/emulate run.

//go:build mobilebuild

package gomobile

import (
	"embed"

	"{{.ModuleName}}/backend/app"
	"github.com/daforester/goleo/runtime"
)

//go:embed all:frontend/dist
var frontendFS embed.FS

var goleoApp *runtime.App

// StartServer builds and starts the app. devMode is passed in by the native
// shell (see MainActivity.java / AppDelegate.swift): true when launched
// through ` + "`goleo emulate`" + `/dev tooling, false in a release build.
func StartServer(devMode bool) int {
	goleoApp = app.New(app.Options{
		DevMode:    devMode,
		WindowMode: runtime.WindowModeBrowser,
		EmbedFS:    frontendFS,
	})
	port, err := goleoApp.StartServer()
	if err != nil {
		return 0
	}
	return port
}

func StopServer() {
	if goleoApp != nil {
		goleoApp.Stop()
	}
}

// EmitSensorReading delivers one sensor sample to the frontend as a
// goleo:sensorReading event. Call this from the native sensor listener
// (e.g. Android's SensorEventListener.onSensorChanged) after arming a
// sensor via SetSensorsProvider.
func EmitSensorReading(sensorType string, x, y, z float64, timestamp int64) {
	if goleoApp == nil {
		return
	}
	goleoApp.Bridge().Emit("goleo:sensorReading", map[string]any{
		"type":      sensorType,
		"x":         x,
		"y":         y,
		"z":         z,
		"timestamp": timestamp,
	})
}

// EmitBackgroundSync notifies the frontend that a registered background
// sync task actually ran, as a goleo:backgroundSync event. Call this from
// the native task callback (e.g. Android WorkManager's Worker.doWork()).
func EmitBackgroundSync(tag string) {
	if goleoApp == nil {
		return
	}
	goleoApp.Bridge().Emit("goleo:backgroundSync", map[string]any{"tag": tag})
}
`

var tmplMobileNotifierGo = `// Code generated by goleo. DO NOT EDIT.
// This file is regenerated on every goleo dev/build/emulate run.

//go:build mobilebuild

package gomobile

import "github.com/daforester/goleo/runtime"

// Notifier is implemented by the native shell (Android Activity / iOS
// AppDelegate) to deliver system notifications. gomobile generates
// bindings for this interface.
type Notifier interface {
	Show(title string, body string)
	PermissionGranted() bool
	RequestPermission() string
}

// SetNotifier registers the native notification backend. The shell must
// call this at startup so runtime.Notify can reach the OS notification
// service.
func SetNotifier(n Notifier) {
	if n == nil {
		runtime.SetNativeNotifier(nil)
		return
	}
	runtime.SetNativeNotifier(&notifierAdapter{n: n})
}

type notifierAdapter struct{ n Notifier }

func (a *notifierAdapter) Show(title, body string) error {
	a.n.Show(title, body)
	return nil
}

func (a *notifierAdapter) PermissionGranted() bool { return a.n.PermissionGranted() }

func (a *notifierAdapter) RequestPermission() string { return a.n.RequestPermission() }
`

// tmplMobileFeaturesGo has no per-project placeholders and no dependency on
// any permission-gated runtime symbol, so it's always safe to include
// (unlike the per-feature files below, which reference runtime types that
// only exist under their own goleo_* tag — SetHomeDir needs none of those).
var tmplMobileFeaturesGo = `// Code generated by goleo. DO NOT EDIT.
// This file is regenerated on every goleo dev/build/emulate run.

//go:build mobilebuild

package gomobile

import "os"

// SetHomeDir sets the directory Go's os.UserConfigDir/os.UserHomeDir treat
// as $HOME — and by extension what runtime FS's AppDataDir/HomeDir resolve
// against — since the gomobile host process has no $HOME of its own
// (without this, os.UserConfigDir errors outright and os.UserHomeDir falls
// back to "/sdcard" on Android or "/" on iOS, neither a real app directory).
// Call this once at startup, before StartServer, with a real app-writable
// directory: Android Context.getFilesDir().getAbsolutePath(), iOS
// NSHomeDirectory().
func SetHomeDir(path string) {
	os.Setenv("HOME", path)
}
`

// Each of the following per-feature provider files must carry its own
// goleo_* build tag, matching the corresponding runtime/*_reexport.go file
// exactly: runtime.BatteryProvider (etc.) only exists under that tag, so a
// project that disables the feature in app.go (dropping the tag via
// detectFeatureUsage) must also drop the file referencing it — otherwise
// the gomobile package fails to compile instead of gracefully lacking the
// feature. (mobilebuild implies GOOS is always android or ios here, so the
// "!(android||ios) ||" half of the runtime tag is always false and can be
// dropped.)

var tmplMobileBatteryGo = `// Code generated by goleo. DO NOT EDIT.
// This file is regenerated on every goleo dev/build/emulate run.

//go:build mobilebuild && goleo_battery

package gomobile

import "github.com/daforester/goleo/runtime"

// BatteryProvider is implemented by the native shell (Android Activity / iOS
// AppDelegate) to report real battery state. gomobile generates bindings for
// this interface. Level is 0..1 (or -1 if unknown); ChargingTime and
// DischargingTime are seconds (or -1 if unknown/not applicable).
type BatteryProvider interface {
	Level() float64
	Charging() bool
	ChargingTime() float64
	DischargingTime() float64
}

// SetBatteryProvider registers the native battery backend.
func SetBatteryProvider(p BatteryProvider) {
	if p == nil {
		runtime.SetBatteryProvider(nil)
		return
	}
	runtime.SetBatteryProvider(&batteryAdapter{p: p})
}

type batteryAdapter struct{ p BatteryProvider }

func (a *batteryAdapter) GetBatteryInfo() (*runtime.BatteryInfo, error) {
	return &runtime.BatteryInfo{
		Level:           a.p.Level(),
		Charging:        a.p.Charging(),
		ChargingTime:    a.p.ChargingTime(),
		DischargingTime: a.p.DischargingTime(),
	}, nil
}
`

var tmplMobileClipboardGo = `// Code generated by goleo. DO NOT EDIT.
// This file is regenerated on every goleo dev/build/emulate run.

//go:build mobilebuild && goleo_clipboard

package gomobile

import "github.com/daforester/goleo/runtime"

// ClipboardProvider is implemented by the native shell (Android Activity / iOS
// AppDelegate) to read and write the system clipboard. gomobile generates
// bindings for this interface.
type ClipboardProvider interface {
	ReadText() string
	WriteText(text string)
}

// SetClipboardProvider registers the native clipboard backend.
func SetClipboardProvider(p ClipboardProvider) {
	if p == nil {
		runtime.SetClipboardProvider(nil)
		return
	}
	runtime.SetClipboardProvider(&clipboardAdapter{p: p})
}

type clipboardAdapter struct{ p ClipboardProvider }

func (a *clipboardAdapter) ReadText() (string, error) { return a.p.ReadText(), nil }

func (a *clipboardAdapter) WriteText(text string) error {
	a.p.WriteText(text)
	return nil
}
`

var tmplMobileShareGo = `// Code generated by goleo. DO NOT EDIT.
// This file is regenerated on every goleo dev/build/emulate run.

//go:build mobilebuild && goleo_share

package gomobile

import "github.com/daforester/goleo/runtime"

// ShareProvider is implemented by the native shell (Android Activity / iOS
// AppDelegate) to open the system share sheet. gomobile generates bindings for
// this interface.
type ShareProvider interface {
	Share(title, text, url string)
}

// SetShareProvider registers the native share backend.
func SetShareProvider(p ShareProvider) {
	if p == nil {
		runtime.SetShareProvider(nil)
		return
	}
	runtime.SetShareProvider(&shareAdapter{p: p})
}

type shareAdapter struct{ p ShareProvider }

func (a *shareAdapter) Share(data *runtime.ShareData) error {
	a.p.Share(data.Title, data.Text, data.URL)
	return nil
}
`

var tmplMobileWakeLockGo = `// Code generated by goleo. DO NOT EDIT.
// This file is regenerated on every goleo dev/build/emulate run.

//go:build mobilebuild && goleo_wakelock

package gomobile

import "github.com/daforester/goleo/runtime"

// WakeLockProvider is implemented by the native shell to keep the screen
// awake. gomobile generates bindings for this interface. Its method set
// matches runtime.WakeLockProvider exactly, so it satisfies that interface
// directly with no adapter needed.
type WakeLockProvider interface {
	Request(typeName string) error
	Release() error
}

// SetWakeLockProvider registers the native wake-lock backend.
func SetWakeLockProvider(p WakeLockProvider) {
	if p == nil {
		runtime.SetWakeLockProvider(nil)
		return
	}
	runtime.SetWakeLockProvider(p)
}
`

var tmplMobileSensorsGo = `// Code generated by goleo. DO NOT EDIT.
// This file is regenerated on every goleo dev/build/emulate run.

//go:build mobilebuild && goleo_sensors

package gomobile

import "github.com/daforester/goleo/runtime"

// SensorsProvider is implemented by the native shell (Android SensorManager
// / iOS CoreMotion) to start/stop motion sensor streaming. Its method set
// matches runtime.SensorsProvider exactly, so it satisfies that interface
// directly with no adapter needed. Deliver each reading by calling
// EmitSensorReading (in gomobile.go) from the native listener callback.
type SensorsProvider interface {
	StartSensor(sensorType string) error
	StopSensor(sensorType string) error
}

// SetSensorsProvider registers the native sensors backend.
func SetSensorsProvider(p SensorsProvider) {
	if p == nil {
		runtime.SetSensorsProvider(nil)
		return
	}
	runtime.SetSensorsProvider(p)
}
`

var tmplMobileBackgroundGo = `// Code generated by goleo. DO NOT EDIT.
// This file is regenerated on every goleo dev/build/emulate run.

//go:build mobilebuild && goleo_background

package gomobile

import "github.com/daforester/goleo/runtime"

// BackgroundProvider is implemented by the native shell (Android WorkManager
// / iOS BGTaskScheduler) to run tasks when connectivity returns. Its method
// set matches runtime.BackgroundProvider exactly, so it satisfies that
// interface directly with no adapter needed. Call EmitBackgroundSync (in
// gomobile.go) from the native task callback when a registered sync task
// actually runs.
type BackgroundProvider interface {
	RegisterSync(tag string) error
	GetPermission() bool
	RequestPermission() error
}

// SetBackgroundProvider registers the native background-sync backend.
func SetBackgroundProvider(p BackgroundProvider) {
	if p == nil {
		runtime.SetBackgroundProvider(nil)
		return
	}
	runtime.SetBackgroundProvider(p)
}
`

var tmplMobileNFCGo = `// Code generated by goleo. DO NOT EDIT.
// This file is regenerated on every goleo dev/build/emulate run.

//go:build mobilebuild && goleo_nfc

package gomobile

import (
	"encoding/json"

	"github.com/daforester/goleo/runtime"
)

// NFCProvider is implemented by the native shell (Android NfcAdapter / iOS
// CoreNFC) to scan and write NFC tags. gomobile generates bindings for this
// interface. WriteJSON takes a JSON-encoded runtime.NFCMessage — gomobile
// can't bind a method parameter containing a slice of a custom struct
// (NFCMessage.Records []NFCRecord), so the message crosses the binding
// boundary as a plain string instead.
type NFCProvider interface {
	StartScan() error
	StopScan() error
	WriteJSON(messageJSON string) error
}

// SetNFCProvider registers the native NFC backend.
func SetNFCProvider(p NFCProvider) {
	if p == nil {
		runtime.SetNFCProvider(nil)
		return
	}
	runtime.SetNFCProvider(&nfcAdapter{p: p})
}

type nfcAdapter struct{ p NFCProvider }

func (a *nfcAdapter) StartScan() error { return a.p.StartScan() }
func (a *nfcAdapter) StopScan() error  { return a.p.StopScan() }

func (a *nfcAdapter) Write(message runtime.NFCMessage) error {
	data, err := json.Marshal(message)
	if err != nil {
		return err
	}
	return a.p.WriteJSON(string(data))
}

// EmitNFCTag delivers a scanned tag's UID to the frontend as a "nfc:tag"
// event. Call this from the native tag-discovery callback (e.g. Android's
// onNewIntent handling NfcAdapter.EXTRA_TAG) after arming a scan via
// SetNFCProvider.
func EmitNFCTag(uid string) {
	runtime.EmitNFCTag(uid)
}
`

var tmplMobileBLEGo = `// Code generated by goleo. DO NOT EDIT.
// This file is regenerated on every goleo dev/build/emulate run.

//go:build mobilebuild && goleo_ble

package gomobile

import (
	"encoding/json"

	"github.com/daforester/goleo/runtime"
)

// BLEProvider is implemented by the native shell (Android
// BluetoothLeScanner+BluetoothGatt / iOS CoreBluetooth) to discover and
// talk to BLE peripherals. gomobile generates bindings for this interface.
// RequestDeviceJSON takes a JSON-encoded filter map and returns a
// JSON-encoded runtime.BLEDevice — gomobile can't bind a map[string]any
// parameter at all, and separately, gobind cannot generate a reverse-bound
// (Java-implemented) proxy method that returns a pointer to a struct
// defined in a different package than the interface itself (confirmed via
// an isolated gomobile bind run: the generated proxy silently omits the
// method entirely, producing a "does not implement" compile error) — so
// both the filters and the returned device cross the binding boundary as
// plain strings instead.
type BLEProvider interface {
	RequestDeviceJSON(filtersJSON string) (string, error)
	Connect(deviceID string) error
	Disconnect(deviceID string) error
	Read(deviceID, service, characteristic string) ([]byte, error)
	Write(deviceID, service, characteristic string, data []byte) error
}

// SetBLEProvider registers the native BLE backend.
func SetBLEProvider(p BLEProvider) {
	if p == nil {
		runtime.SetBLEProvider(nil)
		return
	}
	runtime.SetBLEProvider(&bleAdapter{p: p})
}

type bleAdapter struct{ p BLEProvider }

func (a *bleAdapter) RequestDevice(filters map[string]any) (*runtime.BLEDevice, error) {
	filterData, err := json.Marshal(filters)
	if err != nil {
		return nil, err
	}
	deviceJSON, err := a.p.RequestDeviceJSON(string(filterData))
	if err != nil {
		return nil, err
	}
	var device runtime.BLEDevice
	if err := json.Unmarshal([]byte(deviceJSON), &device); err != nil {
		return nil, err
	}
	return &device, nil
}

func (a *bleAdapter) Connect(deviceID string) error    { return a.p.Connect(deviceID) }
func (a *bleAdapter) Disconnect(deviceID string) error { return a.p.Disconnect(deviceID) }

func (a *bleAdapter) Read(deviceID, service, characteristic string) ([]byte, error) {
	return a.p.Read(deviceID, service, characteristic)
}

func (a *bleAdapter) Write(deviceID, service, characteristic string, data []byte) error {
	return a.p.Write(deviceID, service, characteristic, data)
}
`
