// Auto-generated by `goleo generate types`
// Do not edit manually. Re-run `goleo generate types` to update.

import type { OSInfo, PlatformInfo } from '@goleo/bridge'

/* eslint-disable */

declare module '@goleo/bridge' {
  interface Bridge {
    invoke(method: 'goleo:getOS'): Promise<{ os: string; arch: string; name: string; version?: string }>
    invoke(method: 'goleo:getPlatform'): Promise<{ platform: string; isMobile: boolean; isDesktop: boolean; isBrowser: boolean }>
    invoke(method: 'goleo:getArch'): Promise<string>
    invoke(method: 'goleo:getEnv', args: { key: string }): Promise<string>
    invoke(method: 'goleo:openURL', args: { url: string }): Promise<void>
    invoke(method: 'goleo:notify', args: { title: string; body?: string }): Promise<void>
    invoke(method: 'goleo:notificationPermissionGranted'): Promise<boolean>
    invoke(method: 'goleo:requestNotificationPermission'): Promise<'granted' | 'denied' | 'default'>
    invoke(method: 'goleo:showMessage', args: { title: string; message: string }): Promise<void>
    invoke(method: 'goleo:clipboardReadText'): Promise<{ text: string }>
    invoke(method: 'goleo:clipboardWriteText', args: { text: string }): Promise<void>
    invoke(method: 'goleo:dialogOpenFile', args: { title?: string; defaultPath?: string; filters?: { name: string; patterns: string[] }[]; multiple?: boolean }): Promise<string[]>
    invoke(method: 'goleo:dialogSaveFile', args: { title?: string; defaultPath?: string; filters?: { name: string; patterns: string[] }[] }): Promise<string>
    invoke(method: 'goleo:dialogSelectFolder', args: { title?: string; defaultPath?: string }): Promise<string>
    invoke(method: 'goleo:dialogShowMessage', args: { title?: string; message: string; icon?: 'info' | 'warning' | 'error' | 'question'; buttons?: string[] }): Promise<{ button: string }>
    invoke(method: 'goleo:dialogShowPrompt', args: { title?: string; message: string; defaultValue?: string }): Promise<string>
    invoke(method: 'goleo:fsReadTextFile', args: { path: string }): Promise<string>
    invoke(method: 'goleo:fsWriteTextFile', args: { path: string; content: string }): Promise<void>
    invoke(method: 'goleo:fsReadBinaryFile', args: { path: string }): Promise<{ data: string }>
    invoke(method: 'goleo:fsWriteBinaryFile', args: { path: string; data: string }): Promise<void>
    invoke(method: 'goleo:fsListDir', args: { path: string }): Promise<{ name: string; path: string; isDir: boolean; size: number; modTime: string }[]>
    invoke(method: 'goleo:fsDelete', args: { path: string }): Promise<void>
    invoke(method: 'goleo:fsAppDataDir', args: { appName?: string }): Promise<string>
    invoke(method: 'goleo:fsHomeDir'): Promise<string>
    invoke(method: 'goleo:geolocationGetCurrentPosition', args: { enableHighAccuracy?: boolean; timeout?: number; maximumAge?: number }): Promise<{ latitude: number; longitude: number; accuracy?: number }>
    invoke(method: 'goleo:batteryGetInfo'): Promise<{ level: number; charging: boolean; chargingTime?: number; dischargingTime?: number }>
    invoke(method: 'goleo:wakeLockRequest', args: { type?: string }): Promise<void>
    invoke(method: 'goleo:wakeLockRelease'): Promise<void>
    invoke(method: 'goleo:vibrate', args: { pattern: number[] }): Promise<void>
    invoke(method: 'goleo:sensorStart', args: { type: string }): Promise<void>
    invoke(method: 'goleo:sensorStop', args: { type: string }): Promise<void>
    invoke(method: 'goleo:cameraCapturePhoto', args: { width?: number; height?: number }): Promise<{ data: string; format: string }>
    invoke(method: 'goleo:cameraStartStream', args: { width?: number; height?: number }): Promise<void>
    invoke(method: 'goleo:cameraStopStream'): Promise<void>
    invoke(method: 'goleo:bleRequestDevice', args: { filters?: Record<string, unknown> }): Promise<{ id: string; name: string; rssi?: number }>
    invoke(method: 'goleo:bleConnect', args: { deviceId: string }): Promise<void>
    invoke(method: 'goleo:bleDisconnect', args: { deviceId: string }): Promise<void>
    invoke(method: 'goleo:bleRead', args: { deviceId: string; service: string; characteristic: string }): Promise<{ data: string }>
    invoke(method: 'goleo:bleWrite', args: { deviceId: string; service: string; characteristic: string; data: string }): Promise<void>
    invoke(method: 'goleo:nfcStartScan'): Promise<void>
    invoke(method: 'goleo:nfcStopScan'): Promise<void>
    invoke(method: 'goleo:nfcWrite', args: { records: { type: string; mediaType: string; data: string }[] }): Promise<void>
    invoke(method: 'goleo:backgroundRegisterSync', args: { tag: string }): Promise<void>
    invoke(method: 'goleo:backgroundPermissionGranted'): Promise<boolean>
    invoke(method: 'goleo:backgroundRequestPermission'): Promise<void>
    invoke(method: 'goleo:pushSubscribe', args: { serverKey?: string }): Promise<{ endpoint: string; keys: Record<string, string> }>
    invoke(method: 'goleo:pushUnsubscribe'): Promise<void>
    invoke(method: 'goleo:pushGetSubscription'): Promise<{ endpoint: string; keys: Record<string, string> } | null>
  }
}

declare module '@goleo/bridge' {
  export function invoke<T = unknown>(method: string, args?: Record<string, unknown>): Promise<T>
  export function invoke(method: 'goleo:getOS'): Promise<{ os: string; arch: string; name: string; version?: string }>
  export function invoke(method: 'goleo:getPlatform'): Promise<{ platform: string; isMobile: boolean; isDesktop: boolean; isBrowser: boolean }>
  export function invoke(method: 'goleo:getArch'): Promise<string>
  export function invoke(method: 'goleo:getEnv', args: { key: string }): Promise<string>
  export function invoke(method: 'goleo:openURL', args: { url: string }): Promise<void>
  export function invoke(method: 'goleo:notify', args: { title: string; body?: string }): Promise<void>
  export function invoke(method: 'goleo:notificationPermissionGranted'): Promise<boolean>
  export function invoke(method: 'goleo:requestNotificationPermission'): Promise<'granted' | 'denied' | 'default'>
  export function invoke(method: 'goleo:showMessage', args: { title: string; message: string }): Promise<void>
  export function invoke(method: 'goleo:clipboardReadText'): Promise<{ text: string }>
  export function invoke(method: 'goleo:clipboardWriteText', args: { text: string }): Promise<void>
  export function invoke(method: 'goleo:dialogOpenFile', args: { title?: string; defaultPath?: string; filters?: { name: string; patterns: string[] }[]; multiple?: boolean }): Promise<string[]>
  export function invoke(method: 'goleo:dialogSaveFile', args: { title?: string; defaultPath?: string; filters?: { name: string; patterns: string[] }[] }): Promise<string>
  export function invoke(method: 'goleo:dialogSelectFolder', args: { title?: string; defaultPath?: string }): Promise<string>
  export function invoke(method: 'goleo:dialogShowMessage', args: { title?: string; message: string; icon?: 'info' | 'warning' | 'error' | 'question'; buttons?: string[] }): Promise<{ button: string }>
  export function invoke(method: 'goleo:dialogShowPrompt', args: { title?: string; message: string; defaultValue?: string }): Promise<string>
  export function invoke(method: 'goleo:fsReadTextFile', args: { path: string }): Promise<string>
  export function invoke(method: 'goleo:fsWriteTextFile', args: { path: string; content: string }): Promise<void>
  export function invoke(method: 'goleo:fsReadBinaryFile', args: { path: string }): Promise<{ data: string }>
  export function invoke(method: 'goleo:fsWriteBinaryFile', args: { path: string; data: string }): Promise<void>
  export function invoke(method: 'goleo:fsListDir', args: { path: string }): Promise<{ name: string; path: string; isDir: boolean; size: number; modTime: string }[]>
  export function invoke(method: 'goleo:fsDelete', args: { path: string }): Promise<void>
  export function invoke(method: 'goleo:fsAppDataDir', args: { appName?: string }): Promise<string>
  export function invoke(method: 'goleo:fsHomeDir'): Promise<string>
  export function invoke(method: 'goleo:geolocationGetCurrentPosition', args: { enableHighAccuracy?: boolean; timeout?: number; maximumAge?: number }): Promise<{ latitude: number; longitude: number; accuracy?: number }>
  export function invoke(method: 'goleo:batteryGetInfo'): Promise<{ level: number; charging: boolean; chargingTime?: number; dischargingTime?: number }>
  export function invoke(method: 'goleo:wakeLockRequest', args: { type?: string }): Promise<void>
  export function invoke(method: 'goleo:wakeLockRelease'): Promise<void>
  export function invoke(method: 'goleo:vibrate', args: { pattern: number[] }): Promise<void>
  export function invoke(method: 'goleo:sensorStart', args: { type: string }): Promise<void>
  export function invoke(method: 'goleo:sensorStop', args: { type: string }): Promise<void>
  export function invoke(method: 'goleo:cameraCapturePhoto', args: { width?: number; height?: number }): Promise<{ data: string; format: string }>
  export function invoke(method: 'goleo:cameraStartStream', args: { width?: number; height?: number }): Promise<void>
  export function invoke(method: 'goleo:cameraStopStream'): Promise<void>
  export function invoke(method: 'goleo:bleRequestDevice', args: { filters?: Record<string, unknown> }): Promise<{ id: string; name: string; rssi?: number }>
  export function invoke(method: 'goleo:bleConnect', args: { deviceId: string }): Promise<void>
  export function invoke(method: 'goleo:bleDisconnect', args: { deviceId: string }): Promise<void>
  export function invoke(method: 'goleo:bleRead', args: { deviceId: string; service: string; characteristic: string }): Promise<{ data: string }>
  export function invoke(method: 'goleo:bleWrite', args: { deviceId: string; service: string; characteristic: string; data: string }): Promise<void>
  export function invoke(method: 'goleo:nfcStartScan'): Promise<void>
  export function invoke(method: 'goleo:nfcStopScan'): Promise<void>
  export function invoke(method: 'goleo:nfcWrite', args: { records: { type: string; mediaType: string; data: string }[] }): Promise<void>
  export function invoke(method: 'goleo:backgroundRegisterSync', args: { tag: string }): Promise<void>
  export function invoke(method: 'goleo:backgroundPermissionGranted'): Promise<boolean>
  export function invoke(method: 'goleo:backgroundRequestPermission'): Promise<void>
  export function invoke(method: 'goleo:pushSubscribe', args: { serverKey?: string }): Promise<{ endpoint: string; keys: Record<string, string> }>
  export function invoke(method: 'goleo:pushUnsubscribe'): Promise<void>
  export function invoke(method: 'goleo:pushGetSubscription'): Promise<{ endpoint: string; keys: Record<string, string> } | null>
}
